import os
import io
import datetime
import pandas as pd
import streamlit as st

# Set up clean browser window configurations
st.set_page_config(page_title="Semester Attendance Tracker", layout="wide")

# ─── ACCESS & ROLE CONTROL BLOCK ───
def check_password():
    """Returns True if the user enters a valid passcode, and assigns a role."""
    if "password_correct" not in st.session_state:
        st.session_state.password_correct = False
        st.session_state.user_role = "viewer"  # Default fallback

    # If already logged in, bypass screen
    if st.session_state.password_correct:
        return True

    st.subheader("🔒 Secure Portal Access Required")
    user_password = st.text_input("Enter Passcode:", type="password")
    
    if st.button("Verify Key"):
        # Fetch codes safely from your Streamlit encrypted secrets manager
        admin_key = st.secrets["access_password"]
        viewer_key = st.secrets.get("viewer_password", "view123") 
        
        if user_password == admin_key:
            st.session_state.password_correct = True
            st.session_state.user_role = "admin"
            st.rerun()
        elif user_password == viewer_key:
            st.session_state.password_correct = True
            st.session_state.user_role = "viewer"
            st.rerun()
        else:
            st.error("❌ Invalid Key. Access Denied.")
            
    return False

# Stop execution right here if the login fails
if not check_password():
    st.stop()
# ───────────────────────────────────────────────────

# App Banner Header
st.title("🎈 Student-Supervisor Attendance Portal")
role_badge = "🛠️ ADMIN ACCESS" if st.session_state.user_role == "admin" else "👁️ READ-ONLY ACCESS"
st.markdown(f"Collaborative Web Dashboard for Academic Term Monitoring | **Current Role:** `{role_badge}`")
st.divider()

# GLOBAL CONSTANT - Linked to your actual uploaded tracking version
TARGET_EXCEL_FILE = "Semester_Attendance_Tracker_v6.xlsx"

# Load the Excel file database generated by your previous script
@st.cache_data
def load_data():
    df = pd.read_excel(
        TARGET_EXCEL_FILE, 
        sheet_name="Attendance Ledger", 
        skiprows=12,
        dtype={
            "Attendance Log (P/A/L)": str,
            "Comments / Reason for Absence": str
        }
    )
    df["Attendance Log (P/A/L)"] = df["Attendance Log (P/A/L)"].fillna("")
    df["Comments / Reason for Absence"] = df["Comments / Reason for Absence"].fillna("")
    df = df.dropna(how='all', axis=0)
    return df

try:
    # 1. Load the baseline dataset from Excel
    base_df = load_data()
    
    # 2. Set up active session memory state so edits stick around instantly
    if "working_df" not in st.session_state:
        st.session_state.working_df = base_df.copy()

    # 3. INTERACTIVE STATE TRACKER INTERCEPTOR
    if st.session_state.user_role == "admin" and "attendance_editor" in st.session_state and st.session_state.attendance_editor:
        changes_detected = st.session_state.attendance_editor["edited_rows"]
        if changes_detected:
            for row_idx, changes in changes_detected.items():
                for col_name, new_val in changes.items():
                    st.session_state.working_df.at[row_idx, col_name] = new_val

    active_df = st.session_state.working_df

    # 4. RUN LIVE GLOBAL CALCULATIONS
    total_conducted = active_df["Attendance Log (P/A/L)"].dropna().isin(['P', 'A', 'L']).sum()
    total_attended = (active_df["Attendance Log (P/A/L)"] == "P").sum()
    total_absent = (active_df["Attendance Log (P/A/L)"] == "A").sum()
    
    rate = (total_attended / total_conducted) if total_conducted > 0 else 0.0
    status_text = "ELIGIBLE ✅" if rate >= 0.75 else "SHORTAGE ⚠️"
    
    # 5. RENDER GLOBAL METRICS AT TOP OF PAGE
    col1, col2, col3, col4 = st.columns(4)
    with col1:
        st.metric(label="Total Sessions Conducted", value=int(total_conducted))
    with col2:
        st.metric(label="Total Attended Sessions (P)", value=int(total_attended))
    with col3:
        st.metric(label="Total Absences (A)", value=int(total_absent))
    with col4:
        st.metric(label="Running Attendance Rate", value=f"{rate:.1%}", delta=status_text, delta_color="normal" if rate >= 0.75 else "inverse")
        
    st.divider()
    
    # 6. Subject-Wise Sidebar Breakdown Grid
    st.sidebar.header("🎯 Subject Metrics Tracker")
    st.sidebar.markdown("---")
    
    subjects = ["UEC3361", "UGE3386", "UEC3301", "UEC3302", "UEC3303", "UMA3362", "LAB"]
    for subj in subjects:
        subj_present = ((active_df["Course Module"] == subj) & (active_df["Attendance Log (P/A/L)"] == "P")).sum()
        subj_absent = ((active_df["Course Module"] == subj) & (active_df["Attendance Log (P/A/L)"] == "A")).sum()
        
        st.sidebar.subheader(f"📘 {subj}")
        sb_col1, sb_col2 = st.sidebar.columns(2)
        with sb_col1:
            st.sidebar.write(f"🟢 **Present:** {subj_present}")
        with sb_col2:
            st.sidebar.write(f"🔴 **Absent:** {subj_absent}")
        st.sidebar.markdown("---")
        
    # 7. INTERACTIVE DATA GRID FOR COLLABORATION
    st.subheader("🗓️ Academic Calendar Ledger Logs")
    
    if st.session_state.user_role == "admin":
        st.info("💡 Double-click any cell in the green column to log attendance. The metrics will adjust instantly.")
        disabled_columns = ["Date", "Day", "Period Slot", "Start Time", "End Time", "Course Module"]
    else:
        st.warning("🔒 You are in View-Only mode. Editing has been restricted.")
        disabled_columns = active_df.columns.tolist()
    
    # Render spreadsheet grid
    edited_output = st.data_editor(
        active_df,
        disabled=disabled_columns,
        column_config={
            "Attendance Log (P/A/L)": st.column_config.SelectboxColumn(
                "Attendance Log (P/A/L)",
                help="Select status key",
                options=["P", "A", "L"],
                required=False,
            ),
            "Comments / Reason for Absence": st.column_config.TextColumn(
                "Comments / Reason for Absence",
                width="large"
            )
        },
        use_container_width=True,
        num_rows="fixed",
        key="attendance_editor"
    )

    # 8. UPGRADED: COMMIT PERMANENT SAVE ACTION WITH AUDIT LOGGING
    if st.session_state.user_role == "admin":
        st.divider()
        st.subheader("🛠️ Administrative Controls")
        
        admin_col1, admin_col2 = st.columns(2)
        
        with admin_col1:
            if st.button("💾 Save System Changes permanently", use_container_width=True):
                import openpyxl
                wb = openpyxl.load_workbook(TARGET_EXCEL_FILE)
                ws = wb["Attendance Ledger"]
                
                # Check or initialize the "Change History" sheet inside the Excel workbook
                if "Change History" not in wb.sheetnames:
                    ws_history = wb.create_sheet(title="Change History")
                    ws_history.append(["Timestamp", "Excel Row Index", "Course Module", "Field Modified", "Old Value", "New Value"])
                else:
                    ws_history = wb["Change History"]
                
                now_str = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
                logged_changes_count = 0
                
                # ─── GRANULAR CELL-BY-CELL COMPARISON ENGINE ───
                for idx, row in active_df.iterrows():
                    excel_row = 14 + idx
                    
                    # Columns to audit check
                    columns_to_check = {
                        "Attendance Log (P/A/L)": 7,
                        "Comments / Reason for Absence": 8
                    }
                    
                    for col_name, col_num in columns_to_check.items():
                        new_val = str(row[col_name]).strip()
                        old_val = str(base_df.at[idx, col_name]).strip()
                        
                        # If a real structural shift occurred in text content, record it
                        if new_val != old_val:
                            # 1. Update primary attendance tracker cell data
                            ws.cell(row=excel_row, column=col_num, value=row[col_name])
                            
                            # 2. Append cell-level metrics row into the History sheet
                            ws_history.append([
                                now_str, 
                                f"Row {excel_row}", 
                                row.get("Course Module", "N/A"), 
                                col_name, 
                                old_val if old_val else "[Blank Entry]", 
                                new_val if new_val else "[Cleared Entry]"
                            ])
                            logged_changes_count += 1
                
                # Fallback safeguard: if user hits save without modifying text, execute baseline save
                if logged_changes_count == 0:
                    for idx, row in active_df.iterrows():
                        excel_row = 14 + idx
                        ws.cell(row=excel_row, column=7, value=row["Attendance Log (P/A/L)"])
                        ws.cell(row=excel_row, column=8, value=row["Comments / Reason for Absence"])
                
                wb.save(TARGET_EXCEL_FILE)
                
                if logged_changes_count > 0:
                    st.success(f"🎉 Ledger stored! {logged_changes_count} individual cell changes successfully logged inside the 'Change History' sheet.")
                else:
                    st.success("Attendance ledger saved. No text modifications detected since last snapshot.")
                
                st.cache_data.clear()
                
        with admin_col2:
            if st.button("🔄 Reset Memory (Discard Unsaved Edits)", use_container_width=True):
                if "working_df" in st.session_state:
                    del st.session_state.working_df
                st.cache_data.clear()
                st.rerun()
                
        st.markdown("---")
        # 9. LOCAL HARD DRIVE DOWNLOAD WIDGET (Admin Only)
        if os.path.exists(TARGET_EXCEL_FILE):
            with open(TARGET_EXCEL_FILE, "rb") as file:
                file_bytes = file.read()
                st.download_button(
                    label="📥 Download Updated Excel File to Local Computer",
                    data=file_bytes,
                    file_name=TARGET_EXCEL_FILE,
                    mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                    use_container_width=True
                )

except FileNotFoundError:
    st.error(f"⚠️ Error: Could not locate your base tracking Excel file ({TARGET_EXCEL_FILE}) in the active repository path.")
