import os
import io
import pandas as pd
import streamlit as st

# Set up clean browser window configurations
st.set_page_config(page_title="Semester Attendance Tracker", layout="wide")

# ─── PASSWORD SECURITY BLOCK AT THE TOP ───
def check_password():
    """Returns True if the user had the correct password."""
    if "password_correct" not in st.session_state:
        st.session_state.password_correct = False

    # If password is already verified, bypass the lock screen
    if st.session_state.password_correct:
        return True

    # Show the login form input fields
    st.subheader("🔒 Secure Portal Access Required")
    user_password = st.text_input("Enter Passcode:", type="password")
    
    if st.button("Verify Key"):
        # We link this to Streamlit's encrypted cloud system secrets manager
        if user_password == st.secrets["access_password"]:
            st.session_state.password_correct = True
            st.rerun()
        else:
            st.error("❌ Invalid Key. Access Denied.")
            
    return False

# Stop execution right here if the login fails
if not check_password():
    st.stop()
# ───────────────────────────────────────────────────

# App Banner Header
st.title("🎈 Student-Supervisor Attendance Portal")
st.markdown("Collaborative Web Dashboard for Academic Term Monitoring")
st.divider()

# GLOBAL CONSTANT - Linked to your actual uploaded tracking version
TARGET_EXCEL_FILE = "Semester_Attendance_Tracker_v6.xlsx"

# Load the Excel file database generated by your previous script
@st.cache_data
def load_data():
    df = pd.read_excel(
        TARGET_EXCEL_FILE, 
        sheet_name="Attendance Ledger", 
        skiprows=12,
        dtype={
            "Attendance Log (P/A/L)": str,
            "Comments / Reason for Absence": str
        }
    )
    df["Attendance Log (P/A/L)"] = df["Attendance Log (P/A/L)"].fillna("")
    df["Comments / Reason for Absence"] = df["Comments / Reason for Absence"].fillna("")
    df = df.dropna(how='all', axis=0)
    return df

try:
    # 1. Load the baseline dataset from Excel
    base_df = load_data()
    
    # 2. Set up active session memory state so edits stick around instantly
    if "working_df" not in st.session_state:
        st.session_state.working_df = base_df.copy()

    # 3. INTERACTIVE STATE TRACKER INTERCEPTOR
    if "attendance_editor" in st.session_state and st.session_state.attendance_editor:
        changes_detected = st.session_state.attendance_editor["edited_rows"]
        if changes_detected:
            for row_idx, changes in changes_detected.items():
                for col_name, new_val in changes.items():
                    st.session_state.working_df.at[row_idx, col_name] = new_val

    active_df = st.session_state.working_df

    # 4. RUN LIVE GLOBAL CALCULATIONS
    total_conducted = active_df["Attendance Log (P/A/L)"].dropna().isin(['P', 'A', 'L']).sum()
    total_attended = (active_df["Attendance Log (P/A/L)"] == "P").sum()
    total_absent = (active_df["Attendance Log (P/A/L)"] == "A").sum()
    
    rate = (total_attended / total_conducted) if total_conducted > 0 else 0.0
    status_text = "ELIGIBLE ✅" if rate >= 0.75 else "SHORTAGE ⚠️"
    
    # 5. RENDER GLOBAL METRICS AT TOP OF PAGE
    col1, col2, col3, col4 = st.columns(4)
    with col1:
        st.metric(label="Total Sessions Conducted", value=int(total_conducted))
    with col2:
        st.metric(label="Total Attended Sessions (P)", value=int(total_attended))
    with col3:
        st.metric(label="Total Absences (A)", value=int(total_absent))
    with col4:
        st.metric(label="Running Attendance Rate", value=f"{rate:.1%}", delta=status_text, delta_color="normal" if rate >= 0.75 else "inverse")
        
    st.divider()
    
    # 6. UPGRADED: Subject-Wise Sidebar Breakdown Grid with Present and Absent metrics
    st.sidebar.header("🎯 Subject Metrics Tracker")
    st.sidebar.markdown("---")
    
    subjects = ["UEC3361", "UGE3386", "UEC3301", "UEC3302", "UEC3303", "UMA3362", "LAB"]
    for subj in subjects:
        # Calculate individual metrics dynamically
        subj_present = ((active_df["Course Module"] == subj) & (active_df["Attendance Log (P/A/L)"] == "P")).sum()
        subj_absent = ((active_df["Course Module"] == subj) & (active_df["Attendance Log (P/A/L)"] == "A")).sum()
        
        # Display each subject as a distinct clean card block
        st.sidebar.subheader(f"📘 {subj}")
        sb_col1, sb_col2 = st.sidebar.columns(2)
        with sb_col1:
            st.sidebar.write(f"🟢 **Present:** {subj_present}")
        with sb_col2:
            st.sidebar.write(f"🔴 **Absent:** {subj_absent}")
        st.sidebar.markdown("---")
        
    # 7. INTERACTIVE DATA GRID FOR COLLABORATION
    st.subheader("🗓️ Academic Calendar Ledger Logs")
    st.info("💡 Double-click any cell in the green column to log attendance. The metrics will adjust instantly.")
    
    # Render editable spreadsheet linked directly to state memory
    edited_output = st.data_editor(
        active_df,
        disabled=["Date", "Day", "Period Slot", "Start Time", "End Time", "Course Module"],
        column_config={
            "Attendance Log (P/A/L)": st.column_config.SelectboxColumn(
                "Attendance Log (P/A/L)",
                help="Select status key",
                options=["P", "A", "L"],
                required=False,
            ),
            "Comments / Reason for Absence": st.column_config.TextColumn(
                "Comments / Reason for Absence",
                width="large"
            )
        },
        use_container_width=True,
        num_rows="fixed",
        key="attendance_editor"
    )

    # 8. COMMIT PERMANENT SAVE ACTION
    st.divider()
    if st.button("💾 Save System Changes permanently"):
        import openpyxl
        wb = openpyxl.load_workbook(TARGET_EXCEL_FILE)
        ws = wb["Attendance Ledger"]
        
        # Safely map entries down to columns G and H row by row
        for idx, row in active_df.iterrows():
            excel_row = 14 + idx
            ws.cell(row=excel_row, column=7, value=row["Attendance Log (P/A/L)"])
            ws.cell(row=excel_row, column=8, value=row["Comments / Reason for Absence"])
            
        wb.save(TARGET_EXCEL_FILE)
        st.success(f"Attendance ledger modifications saved to the cloud application temporary database!")
        st.cache_data.clear() # Clear cache so changes populate on page reload
        
    # 9. NEW: LOCAL HARD DRIVE DOWNLOAD WIDGET [1]
    if os.path.exists(TARGET_EXCEL_FILE):
        with open(TARGET_EXCEL_FILE, "rb") as file:
            file_bytes = file.read()
            st.download_button(
                label="📥 Download Updated Excel File to Local Computer",
                data=file_bytes,
                file_name=TARGET_EXCEL_FILE,
                mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
            )

except FileNotFoundError:
    st.error(f"⚠️ Error: Could not locate your base tracking Excel file ({TARGET_EXCEL_FILE}) in the active repository path.")
    
    # Auto-Diagnosis display to quickly spot misaligned folder setups
    st.info("🔍 **Directory Inspector Tool:** Here are the exact files detected in your GitHub working folder right now:")
    current_files = os.listdir('.')
    st.write(current_files)
